CREATE TABLE super_heroes (
id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
name TEXT,
description TEXT,
biography TEXT,
alter_ego TEXT,
species TEXT,
CONSTRAINT "super_hero_PK" PRIMARY KEY (id));